### ISSUE TITLE
Compiler error on new warning fix

### ISSUE THREAD

**Issue by fietser28** [eez-open/eez-framework#14]
With the latest [commit](https://github.com/eez-open/eez-framework/commit/7a01ce78cb06c38d668e4873296b5652ec55b43f) getting getting the the following compile errors:

![image](https://github.com/user-attachments/assets/5b9ead9b-d8d6-4f9e-b4d1-e1cbc3f2349e)

Using:
- latest studio commit
- latest eez-framework commit
- Arduino-pico platform on platformio (is using GCC 14.2 toolchain)
all on Mac ARM.

**Comment by mvladic** [comment]
Can you try the following?

```
#if __GNUC__ && defined( __has_warning )
#   if __has_warning( "-Wdangling-pointer" )
#       define SUPPRESSING
#       pragma GCC diagnostic push
#       pragma GCC diagnostic ignored "-Wdangling-pointer"
#   endif
#endif

...

#ifdef SUPPRESSING
#   undef SUPPRESSING
#   pragma GCC diagnostic pop
#endif
```

**Comment by fietser28** [comment]
Works, no warnings or errors.

![image](https://github.com/user-attachments/assets/d135e364-f41f-47bf-836f-debfb5de4dfb)

**Comment by mvladic** [comment]
Fixed.
